"""UTF-8-safe text I/O for every file the launcher reads or generates.

**Why this module exists.** ``Path.read_text()``/``Path.write_text()`` with no
``encoding=`` use ``locale.getencoding()`` — which on Windows is the legacy ANSI
codepage (cp1252 on a typical Western install, cp932/cp936/… elsewhere), *not*
UTF-8. Every consumer of the files the launcher writes requires strict UTF-8:

* the Rust ingestion binary reads ``config.toml`` with ``std::fs::read_to_string``,
  which is UTF-8-only and fails the whole process with
  ``stream did not contain valid UTF-8``;
* TOML itself is defined to be a UTF-8 encoded document.

That combination produced a real, reproducible field failure. The config
``l2arb setup`` generates opens with the comment

    # L2 Arbitrage Bot — Arbitrum quick-start config (generated by `l2arb setup`).

whose em dash (U+2014) encodes under cp1252 to the **single byte 0x97**. A lone
0x97 is not valid UTF-8, so ``l2-ingest`` refused to start on every launch, the
supervisor restarted it, and the health HUD showed ingestion permanently
``failed`` with that exact error while engine and dashboard stayed green. It
reproduces on any Windows box with a Latin-1 codepage — i.e. the default for
most Western installs — and is invisible on POSIX, where the default encoding is
already UTF-8, which is why every test passed.

So: **all** launcher text I/O goes through this module. Reads tolerate a UTF-8
BOM (Windows editors such as Notepad add one, and a BOM is valid UTF-8 but is
*not* valid TOML — it would move the failure from "invalid UTF-8" to an opaque
parse error). Writes emit UTF-8 with no BOM and LF newlines, so a generated file
is byte-identical on every platform.
"""

from __future__ import annotations

import locale
from pathlib import Path

#: Encoding for every file the launcher writes. Not configurable on purpose —
#: the consumers (Rust ``read_to_string``, the TOML spec) do not offer a choice.
ENCODING = "utf-8"

#: Read encoding. ``utf-8-sig`` decodes plain UTF-8 unchanged and additionally
#: strips a leading BOM if one is present.
READ_ENCODING = "utf-8-sig"


def read_text(path: Path) -> str:
    """Read ``path`` as UTF-8, transparently stripping a BOM if present."""
    return Path(path).read_text(encoding=READ_ENCODING)


def write_text(path: Path, text: str) -> None:
    """Write ``text`` to ``path`` as UTF-8 — no BOM, LF newlines, every platform.

    ``newline="\\n"`` disables Python's default newline translation so a config
    generated on Windows is byte-identical to one generated on Linux, keeping
    the output deterministic and diffable.
    """
    Path(path).write_text(text, encoding=ENCODING, newline="\n")


def is_valid_utf8(path: Path) -> bool:
    """True when ``path`` decodes as UTF-8 — i.e. the Rust ingestion binary can
    read it at all. False for a nonexistent/unreadable file, so callers treat
    "can't prove it's good" as "not good"."""
    try:
        Path(path).read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return True


def _legacy_decode(raw: bytes) -> str:
    """Recover text from bytes an older launcher wrote in the platform codepage.

    Tries the codepage that would actually have produced them (the current
    locale's) first, then cp1252 explicitly — the overwhelmingly common Windows
    case, and the one that turns the stray 0x97 back into the em dash it was —
    and finally latin-1, which is total (every byte maps to a codepoint) so this
    never raises and the repair below can never lose the file's contents.
    """
    for enc in (locale.getpreferredencoding(False), "cp1252", "latin-1"):
        try:
            return raw.decode(enc)
        except (UnicodeDecodeError, LookupError):
            continue
    return raw.decode("latin-1", errors="replace")  # pragma: no cover - latin-1 is total


def repair_encoding(path: Path) -> bool:
    """Rewrite ``path`` as UTF-8 if it currently isn't, in place.

    Returns True when a repair was performed, False when the file was already
    valid UTF-8 (or does not exist). This exists so an install already broken by
    the bug described in this module's docstring heals itself on the next launch
    instead of requiring the user to find and delete a file in ``AppData`` —
    they cannot be expected to diagnose a codepage fault from a restart loop.

    The original bytes are kept alongside as ``<name>.bak`` so a mis-guessed
    legacy decode is never a destructive, unrecoverable edit.
    """
    path = Path(path)
    if is_valid_utf8(path):
        return False
    try:
        raw = path.read_bytes()
    except OSError:
        return False
    path.with_suffix(path.suffix + ".bak").write_bytes(raw)
    write_text(path, _legacy_decode(raw))
    return True
